# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=3.3
group=loongly.sclp
archives_base_name=sclp

# Common
minecraft_version=1.21
mod_name=Sodium Chinese Localization Pack
mod_author=LoongLy
mod_id=sclp
license=LGPLv3
description=钠-汉化包 
minecraft_version_range=*
issue_tracker_url=https://github.com/Long-Zixuan/SCLP/issues
modrinth_url=https://modrinth.com/mod/sodium-device-check

# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21
parchment_version=2024.07.28

# Fabric
fabric_version=0.101.0+1.21
fabric_loader_version=0.15.11

# Forge
forge_version=47.3.0
forge_loader_version_range=*

# NeoForge
neoforge_version=21.0.167
neoforge_loader_version_range=*

# Sodium
sodium_version=mc1.21-0.6.0-beta.1

# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
