modLoader = "javafml" #mandatory
loaderVersion = "*" #mandatory
license = "LGPLv3" # Review your options at https://choosealicense.com/.
issueTrackerURL = "https://github.com/Long-Zixuan/Sodium_Chinese_Localization_Package/issues" #optional

[[mods]] #mandatory
modId = "sclp" #mandatory
version = "3.0.3.1" #mandatory
displayName = "Sodium Chinese Localization Mod" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional (see https://docs.neoforged.net/docs/misc/updatechecker/)
displayURL = "https://modrinth.com/mod/mc1.16.5-sodium-chinese-localization-pack" #optional (displayed in the mod UI)
logoFile = "assets/sclp/icon.png" #optional
authors = "LoongLy" #optional
description = '''钠（Sodium）汉化模组 ''' #mandatory (Supports multiline text)

[[mixins]]
config = "sclp.mixins.json"

[[mixins]]
config = "sclp.neoforge.mixins.json"

[[dependencies.sclp]]
modId = "sodium"
type = "required" #mandatory (Can be one of "required", "optional", "incompatible" or "discouraged")
versionRange = "[0.3.0-alpha.3,)"
ordering = "NONE"
side = "CLIENT"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.sclp]
#openGLVersion="[3.2,)"
