modLoader = "javafml"
loaderVersion = "*"
license = "MIT"
issueTrackerURL="https://github.com/Long-Zixuan/Sodium_Chinese_Localization_Package/issues"

[[mods]]
modId = "sclp"

version = "${version}"
displayName = "Sodium Chinese Localized Package"
displayURL="https://modrinth.com/mod/mc1.16.5-sodium-chinese-localization-pack"

logoFile = "iconBig.png" #optional
iconFile = "icon.png"

authors = "LoongLy"

description = '''
钠（Sodium）模组汉化包
'''

[[dependencies.sclp]]
modId = "minecraft"
type = "required"
versionRange = "[26.1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.sclp]]
modId = "sodium"
type = "required"
versionRange = "[0.8.7,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "sclp.mixins.json"

[modproperties.sclp]
"sodium:config_api_user" = "me.loongly.mods.sclp.common.client.options.SCLPConfigBuilder"